arrow-parens: [true, 'ban-single-arg-parens']
jsx-boolean-value: false
one-line: [true, 'check-open-brace', 'check-whitespace']
printWidth: 80
quotemark: [true, 'single', 'jsx-double']
trailingComma: 'all'
tabWidth: 2
semi: false
singleQuote: true
useTabs: false
overrides:
  - files: '*.yma?l'
    options:
      tabWidth: 2
