FROM node:10 as builder

WORKDIR /usr/src/

COPY ./app ./app
COPY ./config ./config
COPY ./static ./static
COPY .babelrc .
COPY .nvmrc .
COPY check-socket.js .
COPY *.config.js ./
COPY *.json ./
COPY *.yaml ./

RUN npm install 2>&1
