component: website
name: site

inputs:
    bucketName: ${env:domain}
    # React application. "hook" runs before deployment to build the source code.  "dist" is the built artifact directory which is uploaded.
    src:
        src: ./
        hook: npm run build
        dist: build
    # Enable this when you want to set a custom domain.
    # Route53 ONLY
    # domain: ${env:domain}
